### ISSUE TITLE
Informations about jobs itself

### ISSUE THREAD

**Issue by nadar** [boehsermoe/luya-module-scheduler#1]
What are those implementations are good for?

```php
	public $path;

	public function rules()
	{
		return array_merge(parent::rules(), [
			[['path'], 'required']
		]);
	}


	public function extraFields()
	{
		return [
			'path'
		];
	}

	public function ngrestExtraAttributeTypes()
	{
		return [
			'path' => 'text',
		];
	}
```

Maybe some more details about this would be good.

I assume a basic jobs only requires the `public function run()` method and the other example is more advanced example?

**Comment by boehsermoe** [comment]
It is a example of a file job where you can configure a path per job in the admin area. 

I used it here for a backup job: https://github.com/boehsermoe/luya-module-backup/blob/master/src/schedules/FileBackupJob.php
Or with more configurations: https://github.com/boehsermoe/luya-module-backup/blob/master/src/schedules/DatanbaseBackupJob.php

But you are right if you have a simple job without any configuration the `run()` method is enough.
I will write some more description how to create schedule jobs.
Thank you for contribute!

**Comment by boehsermoe** [comment]
@nadar I wrote some more documentation and examples https://github.com/boehsermoe/luya-module-scheduler/blob/master/README.md
